# Sync connectghin-mobile/.env -> lib/generated/app_env.dart
# Avoids bundling assets/env/config.env (Windows file-lock during flutter build).

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

$envPath = Join-Path $root '.env'
if (-not (Test-Path $envPath)) {
  Write-Error "Missing .env at $envPath"
}

function Read-DotEnvKey([string]$key) {
  foreach ($line in Get-Content $envPath) {
    $t = $line.Trim()
    if ($t.StartsWith('#') -or -not $t.Contains('=')) { continue }
    $parts = $t.Split('=', 2)
    if ($parts[0].Trim() -eq $key) {
      return $parts[1].Trim()
    }
  }
  return $null
}

function Dart-Field([string]$name, [string]$value) {
  if ([string]::IsNullOrWhiteSpace($value)) {
    return "  static const String? $name = null;"
  }
  $escaped = $value.Replace('\', '\\').Replace("'", "\'")
  return "  static const String $name = '$escaped';"
}

$api = Read-DotEnvKey 'API_BASE_URL'
$google = Read-DotEnvKey 'GOOGLE_SERVER_CLIENT_ID'
$places = Read-DotEnvKey 'GOOGLE_PLACES_API_KEY'

$outDir = Join-Path $root 'lib\generated'
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

$dart = @"
// GENERATED by tool/sync_env_to_asset.cmd — do not edit. Source: .env

abstract final class AppEnvValues {
$(Dart-Field 'apiBaseUrl' $api)
$(Dart-Field 'googleServerClientId' $google)
$(Dart-Field 'googlePlacesApiKey' $places)
}
"@

$dartPath = Join-Path $outDir 'app_env.dart'
Set-Content -Path $dartPath -Value $dart -Encoding utf8
Write-Host "Wrote lib/generated/app_env.dart"
